export const SET_SELECTED_DATE = 'SET_SELECTED_DATE';
export const SET_SELECTED_MONTH = 'SET_SELECTED_MONTH';
export const FORWARD_MONTH = 'FORWARD_MONTH';
export const BACKWARD_MONTH = 'BACKWARD_MONTH';
export const SET_SELECTED_CALENDAR_STATE = 'SET_SELECTED_CALENDAR_STATE';